### ISSUE TITLE
File with comments only contains parse error

### ISSUE THREAD

**Issue by mabar** [mesour-intellij-plugins/neon-nette-issues#19]
`'[Neon] T_COMMENT' or '[Neon] T_INDENT' expected, unexpected end of file` is reported at first character of the last line

```neon
# a
# a
# a
```

![image](https://user-images.githubusercontent.com/20974277/151127378-460de810-2f3d-4164-8091-67af9c6fdfb5.png)

**Comment by mesour** [comment]
Fixed in 1.0.3
