### ISSUE TITLE
Plugin freezes when opening a large file

### ISSUE THREAD

**Issue by vaclavpavek** [mesour-intellij-plugins/neon-nette-issues#26]
**Describe the bug**
Plugin freezes when opening a large file, approx. 20.000 - 30.000 lines.

**Environment**
 - PhpStorm version 2021.3.1
 - Plugin version 1.0.3

**Code**
```
parameters:
	ignoreErrors:
		-
			message: "#^Call to method getMessage\\(\\) on an unknown class Facebook\\\\Exceptions\\\\facebookResponseException\\.$#"
			count: 1
			path: ../sample.php

		# repeat the previous item about 6000 times
```

**Comment by mesour** [comment]
@vaclavpavek Is this problem still persist? If yes, please reopen issue.
