### ISSUE TITLE
Upgrade to PHPStorm 2022.1 downgrades plugin to 1.0.0 from 1.0.3

### ISSUE THREAD

**Issue by mabar** [mesour-intellij-plugins/neon-nette-issues#28]
I think this is JetBrains issue because they should not install older plugin version because it supports larger version range of IDE, but it may also make sense to not restrict upper IDE version in plugin since the expected behavior (installing only plugin version which already supports new IDE version) is broken.

![image](https://user-images.githubusercontent.com/20974277/163726894-de53f6cb-2f52-4d12-93bb-c76bfafa137b.png)

**Comment by spaze** [comment]
FYI new version 1.0.4 has been [released](https://plugins.jetbrains.com/plugin/18387-neon-nette-support/versions/stable/169312) (commenting here for people like me who subscribed to updates so they get a heads up)
