### ISSUE TITLE
Child parameters are not suggested

### ISSUE THREAD

**Issue by dakur** [mesour-intellij-plugins/neon-nette-issues#29]
**Describe the bug**
Child parameters are not suggested when trying to use them.

**Environment:**
 - PhpStorm version 2022.1
 - Plugin version 1.0.4

**Code**
```neon
parameters:
	mailFrom:
		name: "Some Company"
		email: hello@example.com

services:
	- WhateverService(%mailFrom.[Ctrl+Space in here]%)
```

**Screenshots**

![image](https://user-images.githubusercontent.com/9862581/165319160-4630bfe2-fbbb-4abf-af7b-609277c41605.png)

**Additional context**

- It doesn't work even if parameter definition and usage is in the same NEON file.
- When I write the param there by hand and then Ctrl+click it, that works correctly.

**Comment by mesour** [comment]
Fixed
