### ISSUE TITLE
Invalid link to profile at PhpStorm IDE internal Errors dialog

### ISSUE THREAD

**Issue by jakubboucek** [mesour-intellij-plugins/neon-nette-issues#32]
**Describe the bug**
The plugin's metadata probably contains invalid link to `mesour-plugins` profile. When IDE is opening crash report, the link to plugin profile is invalid, just open https://plugins.jetbrains.com/ instead open the [plugin page](https://plugins.jetbrains.com/plugin/18387-neon-nette-support)

**Environment (please complete the following information):**
 - PhpStorm version [e.g. 2022.1.1]
 - Plugin version [e.g. 1.0.4]

**To Reproduce**
1. Just let NEON Nette Support plugin to crash 
2. Open the PhpStorm's error detail (window named `IDE Internal Errors`)
3. Click to `mesours-plugin` link

**Code**
Not relevant

**Screenshots**
![](https://cdn.jakub-boucek.cz/screenshot/220520-togli.png)

**Additional context**
Not relevant

**Comment by mesour** [comment]
I will look into it in the next version, it should be fixed.

**Comment by mesour** [comment]
Now you can report issue direct via button in bottom right. Link under mesour-pluings is under JetBrains manage.
