### ISSUE TITLE
Unused parameters if parent parameter is used

### ISSUE THREAD

**Issue by SendiMyrkr** [mesour-intellij-plugins/neon-nette-issues#4]
When i have some structure in parameters which i put to some class as whole then i still see "Unused parameters" on it's sub elements. I think that when i use some parameter than it's child should be marked as used.
![neon-unused-parameters](https://user-images.githubusercontent.com/1462122/149193854-b38bddca-ac27-4a15-bef3-520dd3fbe65d.png)

**Comment by mesour** [comment]
Fixed in 1.1.0
