### ISSUE TITLE
False positive syntax error when using functions via ::function

### ISSUE THREAD

**Issue by lulco** [mesour-intellij-plugins/neon-nette-issues#47]
**Describe the bug**
We're using function calls in services setup. Plugin marks it as wrong syntax and everything after this place is not working (I can't click to classes, got no suggestions etc.)

**Environment (please complete the following information):**
 - PhpStorm version: 2022.2.4 (but I'm pretty sure it is the same with any version)
 - Plugin version: 1.0.5 (but I'm pretty sure it is the same with any version)

**Code to Reproduce**
Add function call to neon:
```
services:
    -
        factory: Foo\Bar\Baz
        arguments:
            qwerty: ::md5(%someParameter%)
```
or

```
services:
    - Foo\Bar\Baz(::md5(%someParameter%))
```

**Screenshots**

<img width="911" alt="image" src="https://user-images.githubusercontent.com/9377319/221295617-94ba3f31-e9a8-438d-97cd-19d7cbab07f2.png">

**Additional context**

Error message I got: "<class usage>, <constant>, <entity key>, <key usage>, <scalar>, <statement>, <string>, <symbol>, '[Neon] T_COMMENT', '[Neon] T_INDENT', '[Neon] T_PARAMETER_LEFT' or '[Neon] T_STATIC_IDENTIFIER' expected, got 'md5'"

Real project example: https://github.com/efabrica-team/phpstan-latte/blob/main/extension.neon#L94

**Comment by mesour** [comment]
Implemented in 1.1.0
