### ISSUE TITLE
Multiple class decladation

### ISSUE THREAD

**Issue by vitvavra** [mesour-intellij-plugins/neon-nette-issues#8]
**Describe the bug**
It shows "Multiple class decladations" as expected, but when you have different configuration files for deployment and for example local it does not respect the inheritance tree of neon files, or rather the scope of the configuration directive

**Environment**
 - PhpStorm version 2021.3.1
 - Plugin version1.0.0

**To Reproduce**
- Create two files with the same content, for example:
```neon
migration:
    namespace: App\Admin\Migration
```
- Create one "master" file with include of one of the two files above

**Comment by mesour** [comment]
@vitvavra I can not reproduce it. Try it in 1.0.7, if problem persist, please reopen issue
